apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-nginx-server
  name: demo-nginx-server
  namespace: demo-application
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-nginx-server
  type: ClusterIP
status:
  loadBalancer: {}
